server:
  port: 8070

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:movietracker}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  thymeleaf:
    prefix: classpath:/static/
  profiles:
    active: dev



