server:
  port: 8070

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:movietracker}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  thymeleaf:
    prefix: classpath:/static/

test-auth:
  test-auth-enabled: true
  persons:
    -
      id: -10
      login: bob
      password: bob
      name: Bob the owner
      selected-profile-id: -10
      is-owner: true
    -
      id: -11
      login: alice
      password: alice
      name: Alice the participant
      selected-profile-id: -10
      is-owner: false

#logging:
#  level:
#    org.springframework.security: DEBUG

